In [2]:
import sys
sys.path.append('d:\projects\hw1_modeling\.venv\lib\site-packages')
import pandas as pd

In [27]:
data = pd.read_csv('../planet/train.csv')

In [28]:
data['Id'] = data['image_name']

In [29]:
data = data[['Id', 'tags']]

In [34]:
all_labels = set()
for s in data['tags']:
    new_labels = s.split(' ')
    all_labels.update(new_labels)

In [35]:
for label in all_labels:
    data[label] = 0

In [36]:
for i, row in data.iterrows():
    for label in row['tags'].split(' '):
        data.loc[i, label] = 1

In [37]:
data

,Id,tags,habitation,cultivation,partly_cloudy,agriculture,cloudy,blooming,slash_burn,selective_logging,blow_down,haze,road,primary,conventional_mine,bare_ground,artisinal_mine,water,clear
0,train_0,haze primary,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0
1,train_1,agriculture clear primary water,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,1
2,train_2,clear primary,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
3,train_3,clear primary,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
4,train_4,agriculture clear habitation primary road,1,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40474,train_40474,clear primary,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1
40475,train_40475,cloudy,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
40476,train_40476,agriculture clear primary,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1
40477,train_40477,agriculture clear primary road,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,1
40478,train_40478,agriculture cultivation partly_cloudy primary,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0

In [38]:
data.to_csv('../planet/train.csv', index=False)